# Generated by Django 4.2.6 on 2023-11-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_girl',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
